 CREATE CACHED TABLE "PUBLIC"."CUSTOMER"(
    "CUSTOMER_ID" SMALLINT NOT NULL,
    "STORE_ID" TINYINT NOT NULL,
    "FIRST_NAME" VARCHAR(45) NOT NULL,
    "LAST_NAME" VARCHAR(45) NOT NULL,
    "EMAIL" VARCHAR(50),
    "ADDRESS_ID" SMALLINT NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "CREATE_DATE" TIMESTAMP NOT NULL,
    "LAST_UPDATE" TIMESTAMP NOT NULL
);          
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("CUSTOMER_ID"); 
CREATE CACHED TABLE "PUBLIC"."FILM"(
    "FILM_ID" SMALLINT NOT NULL,
    "TITLE" VARCHAR(255) NOT NULL,
    "DESCRIPTION" LONGVARCHAR,
    "RELEASE_YEAR" DATE,
    "LANGUAGE_ID" TINYINT NOT NULL,
    "ORIGINAL_LANGUAGE_ID" TINYINT,
    "RENTAL_DURATION" TINYINT NOT NULL,
    "RENTAL_RATE" DECIMAL(4, 2) NOT NULL,
    "LENGTH" SMALLINT,
    "REPLACEMENT_COST" DECIMAL(5, 2) NOT NULL,
    "RATING" VARCHAR(5),
    "SPECIAL_FEATURES" VARCHAR(54),
    "LAST_UPDATE" TIMESTAMP NOT NULL,
AVAILABLE BOOLEAN
);          
ALTER TABLE "PUBLIC"."FILM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("FILM_ID");    